language: go
go:
  - 1.8.x
  - 1.9.x
  - 
  
services:
  - postgresql

before_script:
  - psql -c 'create database medcase_tests;' -U postgres
  - psql -c 'CREATE ROLE medcase_tests WITH LOGIN PASSWORD "medcase_tests"' -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE medcase_tests TO medcase_tests' -U postgres

script:
  # Run the unit tests suite
  - ./go.test.sh
after_success:
  # Send coverage reports to Codecov
  - bash <(curl -s https://codecov.io/bash)