language: go
go:
  - 1.8.x
  - 1.9.x
  - 
  
script:
  # Run the unit tests suite
  - go test -race -coverprofile=coverage.txt -covermode=atomic
after_success:
  # Send coverage reports to Codecov
  - bash <(curl -s https://codecov.io/bash)